name: AIAudioPlayer
options:
  bundleIdPrefix: com.aiaudioplayer
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: 0.9.0

targets:
  AIAudioPlayer:
    type: application
    platform: macOS
    sources:
      - Sources
    dependencies:
      - package: WhisperKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aiaudioplayer.app
        PRODUCT_NAME: AI Audio Player
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: AI Audio Player
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.music
        INFOPLIST_KEY_NSMicrophoneUsageDescription: 用于语音识别功能
        SWIFT_VERSION: "5.9"
        ENABLE_HARDENED_RUNTIME: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"
